language: node_js

node_js:
  - "stable"

services:
  - docker
  - mysql

cache:
  directories:
    - "node_modules"

env:
  global:
    - TEST_DB_HOST=localhost
    - TEST_DB_PORT=5432
    - TEST_DB_USERNAME=postgres
    - TEST_DB_PASSWORD=
    - TEST_DB_NAME=travis_ci_test
    - zipFile = "t_web_700-$TRAVIS_BUILD_NUMBER"
    - publishRegistry = "http://185.216.25.54:32778/service/rest/repository/browse/api-node/t_web_700/$TRAVIS_BUILD_NUMBER/"
    - publishCommand = "curl -u $username:$password --upload-file $zipFile -v $publishRegistry$zipFile.zip"

install:
  - npm install

jobs:
  include:
    - stage: build project zip
      if: branch = master
      script:
        - npm version minor
        - npm publish

notifications:
  email: false
