language: node_js

node_js:
  - "stable"

services:
  - docker
  - mysql

cache:
  directories:
    - "node_modules"

addons:
  apt:
    packages:
      - sshpass

env:
  global:
    - TEST_DB_HOST=localhost
    - TEST_DB_PORT=5432
    - TEST_DB_USERNAME=postgres
    - TEST_DB_PASSWORD=
    - TEST_DB_NAME=travis_ci_test

install:
  - npm install

jobs:
  include:
    - stage: build project zip
      if: branch = master
      script:
        - npm version minor
        - npm publish

    - stage: Deploy on server
      if: branch = master
      script:
        - export SSHPASS=$DEPLOY_PASS
        - sshpass -e scp deploy.sh $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
        - sshpass -e scp package.json $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
        - sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PAT deploy.sh


notifications:
  email: false
